In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from scipy.stats import pearsonr

In [39]:
df = pd.read_excel('/content/Extract.xlsx')

In [40]:
t = 10000
x = np.linspace(1,t,t)
x1=np.array(df['x1'][:t])
x2=np.array(df['x2'][:t])
x3=np.array(df['x3'][:t])
x4=np.array(df['x4'][:t])
x1.shape,x2.shape,x3.shape,x4.shape

((10000,), (10000,), (10000,), (10000,))

In [41]:
#diff = x2[1:]-x2[:t-1] #x2=.35,x3=0.43,x4=0.64
a = np.array([x1,x2,x3,x4]).T
a

array([[3861.22, 3861.66, 3860.75, 3861.38],
       [3861.19, 3861.38, 3860.16, 3861.25],
       [3861.38, 3861.38, 3858.47, 3858.53],
       ...,
       [3794.75, 3795.09, 3794.47, 3794.91],
       [3794.94, 3795.13, 3793.38, 3794.34],
       [3794.31, 3794.66, 3794.06, 3794.47]])

In [42]:
from sklearn.linear_model import LogisticRegression

**Model**

In [43]:
s1 = (a[3:t]-a[2:t-1])[:,3]
s2 = (a[3:t]-a[1:t-2])[:,3]
s3 = (a[3:t]-a[:t-3])[:,3]
r4 = (a[2:t-1][:,0]-a[2:t-1][:,3])
h5 = a[2:t-1][:,1]-a[2:t-1][:,2]
s2 = s2/2
s3 = s3/3

In [44]:
y = np.array(df['y'])[3:]

In [45]:
w = int(t*0.8)
f = np.ones((s1.shape[0],5))
f[:,0] = s1
f[:,1] = s2
f[:,2] = s3
f[:,3] = r4
f[:,4] = h5
train = f[:w]

In [46]:
train

array([[-0.34      , -1.53      , -1.06333333,  2.85      ,  2.91      ],
       [ 0.62      ,  0.14      , -0.81333333,  0.53      ,  1.69      ],
       [ 0.82      ,  0.72      ,  0.36666667, -0.72      ,  1.13      ],
       ...,
       [ 0.59      ,  1.235     ,  0.21666667, -1.97      ,  2.69      ],
       [-3.25      , -1.33      , -0.26      , -0.37      ,  1.82      ],
       [ 0.32      , -1.465     , -0.78      ,  3.1       ,  3.38      ]])

In [47]:
m = LogisticRegression()
m.fit(train,y[:w])

LogisticRegression()

In [48]:
m.score(f[w:],y[w:])

0.5408112168252378

In [49]:
#pickle h5
import pickle
file_name='my_file.pkl'
f = open(file_name,'wb')
pickle.dump(m,f)
f.close()

In [50]:
with open('/content/my_file.pkl', 'rb') as fid:
  data3 = pickle.load(fid)
data3

LogisticRegression()

testing

In [51]:
df = pd.read_excel('/content/test_data_Analytics GC.xlsx')
df.head()

x1       x2       x3       x4
0  3798.66  3798.84  3798.09  3798.16
1  3798.22  3798.78  3798.13  3798.53
2  3798.50  3799.06  3798.28  3798.28
3  3798.31  3798.41  3797.53  3798.06
4  3797.94  3798.78  3797.84  3798.75

In [52]:
x1=np.array(df['x1'][:t])
x2=np.array(df['x2'][:t])
x3=np.array(df['x3'][:t])
x4=np.array(df['x4'][:t])

In [53]:
a = np.array([x1,x2,x3,x4]).T
a

array([[3798.66, 3798.84, 3798.09, 3798.16],
       [3798.22, 3798.78, 3798.13, 3798.53],
       [3798.5 , 3799.06, 3798.28, 3798.28],
       ...,
       [3749.31, 3749.38, 3746.63, 3746.81],
       [3747.03, 3747.28, 3746.  , 3746.31],
       [3745.97, 3746.5 , 3744.81, 3744.88]])

In [54]:
t=1000
s1 = (a[3:t]-a[2:t-1])[:,3]
s2 = (a[3:t]-a[1:t-2])[:,3]
s3 = (a[3:t]-a[:t-3])[:,3]
r4 = (a[2:t-1][:,0]-a[2:t-1][:,3])
h5 = a[2:t-1][:,1]-a[2:t-1][:,2]
s2 = s2/2
s3 = s3/3

In [55]:
f = np.ones((s1.shape[0],5))
f[:,0] = s1
f[:,1] = s2
f[:,2] = s3
f[:,3] = r4
f[:,4] = h5

In [56]:
pd.DataFrame(m.predict(f)).to_csv('pred.csv')

In [57]:
d = pd.read_csv('/content/pred.csv')
d

Unnamed: 0    0
0             0  0.0
1             1  1.0
2             2  0.0
3             3  0.0
4             4  1.0
..          ...  ...
992         992  0.0
993         993  0.0
994         994  0.0
995         995  1.0
996         996  1.0

[997 rows x 2 columns]

In [ ]:
#3:

In [ ]:
# n-1,n-2,n-3 days ka slope (closing price) (slope = close(n)-close(n-k))
# n-1 day ka close-open (return)
# n-1 day high - low
# prediction day 3
# close-open > 0 = 1 else 0

In [ ]:
#m.predict()